name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12  

      # Step 3: Install Python Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r appwrite/backend_scripts/requirements.txt

      # Step 4: Run Database Setup Script
      - name: Run database setup
        env:
          APPWRITE_ENDPOINT: ${{ secrets.APPWRITE_ENDPOINT }}
          APPWRITE_PROJECT_ID: ${{ secrets.APPWRITE_PROJECT_ID }}
          APPWRITE_API_KEY: ${{ secrets.APPWRITE_API_KEY }}
        run: |
          python backend/scripts/main.py

      # Step 5: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # Step 6: Build Frontend
      - name: Build frontend
        working-directory: frontend
        run: |
          npm install
          npm run build

      # Step 7: Deploy Frontend (Optional)
      # - name: Deploy to Vercel
      #   uses: amondnet/vercel-action@v20
      #   with:
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
      #     vercel-args: "--prod"
